site_name: Framework Theory

theme:
  name: material
  palette:
    scheme: slate 
  features:
    - navigation.instant

markdown_extensions:
  - pymdownx.arithmatex 
  - admonition
  - footnotes
  - toc:
      permalink: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Theory: theory.md
